[3m[32m# Do not modify this file!  It was generated by ‘nixos-generate-config’[0m
[3m[32m# and may be overwritten by future invocations.  Please make changes[0m
[3m[32m# to /etc/nixos/configuration.nix instead.[0m
{ config[1m[30m,[0m lib[1m[30m,[0m pkgs[1m[30m,[0m modulesPath[1m[30m,[0m [1m[30m...[0m }:

{
  imports [1m[30m=[0m
    [ (modulesPath [1m[30m+[0m [1m[30m"/installer/scan/not-detected.nix"[0m)
    ];

  boot[1m[30m.[0mkernelPackages [1m[30m=[0m pkgs[1m[30m.[0mlinuxPackages_zen;
  boot[1m[30m.[0minitrd[1m[30m.[0mavailableKernelModules [1m[30m=[0m [ [1m[30m"ahci"[0m [1m[30m"xhci_pci"[0m [1m[30m"usb_storage"[0m [1m[30m"usbhid"[0m [1m[30m"sd_mod"[0m [1m[30m"rtsx_pci_sdmmc"[0m ];
  boot[1m[30m.[0minitrd[1m[30m.[0mkernelModules [1m[30m=[0m [ ];
  boot[1m[30m.[0mkernelModules [1m[30m=[0m [ [1m[30m"kvm-intel"[0m ];
  boot[1m[30m.[0mextraModulePackages [1m[30m=[0m [ ];

  fileSystems[1m[30m.[0m[1m[30m"/"[0m [1m[30m=[0m
    { device [1m[30m=[0m [1m[30m"/dev/disk/by-uuid/9731c052-6851-4460-a678-4605cd211f70"[0m;
      fsType [1m[30m=[0m [1m[30m"btrfs"[0m;
      options [1m[30m=[0m [ [1m[30m"subvol=root"[0m ];
    };

  fileSystems[1m[30m.[0m[1m[30m"/home"[0m [1m[30m=[0m
    { device [1m[30m=[0m [1m[30m"/dev/disk/by-uuid/9731c052-6851-4460-a678-4605cd211f70"[0m;
      fsType [1m[30m=[0m [1m[30m"btrfs"[0m;
      options [1m[30m=[0m [ [1m[30m"subvol=home"[0m ];
    };

  fileSystems[1m[30m.[0m[1m[30m"/nix"[0m [1m[30m=[0m
    { device [1m[30m=[0m [1m[30m"/dev/disk/by-uuid/9731c052-6851-4460-a678-4605cd211f70"[0m;
      fsType [1m[30m=[0m [1m[30m"btrfs"[0m;
      options [1m[30m=[0m [ [1m[30m"subvol=nix"[0m ];
    };

  fileSystems[1m[30m.[0m[1m[30m"/var/log"[0m [1m[30m=[0m
    { device [1m[30m=[0m [1m[30m"/dev/disk/by-uuid/9731c052-6851-4460-a678-4605cd211f70"[0m;
      fsType [1m[30m=[0m [1m[30m"btrfs"[0m;
      options [1m[30m=[0m [ [1m[30m"subvol=log"[0m ];
    };

  fileSystems[1m[30m.[0m[1m[30m"/persist"[0m [1m[30m=[0m
    { device [1m[30m=[0m [1m[30m"/dev/disk/by-uuid/9731c052-6851-4460-a678-4605cd211f70"[0m;
      fsType [1m[30m=[0m [1m[30m"btrfs"[0m;
      options [1m[30m=[0m [ [1m[30m"subvol=persist"[0m ];
    };

  fileSystems[1m[30m.[0m[1m[30m"/boot"[0m [1m[30m=[0m
    { device [1m[30m=[0m [1m[30m"/dev/disk/by-uuid/5BC9-5E1D"[0m;
      fsType [1m[30m=[0m [1m[30m"vfat"[0m;
    };



  [3m[32m# Enables DHCP on each ethernet and wireless interface. In case of scripted networking[0m
  [3m[32m# (the default) this is the recommended approach. When using systemd-networkd it's[0m
  [3m[32m# still possible to use this option, but it's recommended to use it in conjunction[0m
  [3m[32m# with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.[0m
  networking[1m[30m.[0museDHCP [1m[30m=[0m lib[1m[30m.[0mmkDefault [31mtrue[0m;
  [3m[32m# networking.interfaces.enp2s0f1.useDHCP = lib.mkDefault true;[0m
  [3m[32m# networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;[0m

  nixpkgs[1m[30m.[0mhostPlatform [1m[30m=[0m lib[1m[30m.[0mmkDefault [1m[30m"x86_64-linux"[0m;
  hardware[1m[30m.[0mcpu[1m[30m.[0mintel[1m[30m.[0mupdateMicrocode [1m[30m=[0m lib[1m[30m.[0mmkDefault config[1m[30m.[0mhardware[1m[30m.[0menableRedistributableFirmware;

  swapDevices [1m[30m=[0m [  
    {
      device [1m[30m=[0m [1m[30m"/var/lib/swapfile"[0m;
      size [1m[30m=[0m [1m[30m3072[0m;
      [3m[32m# swappiness = 7;[0m
    }
  ];

  nixpkgs[1m[30m.[0mconfig[1m[30m.[0mpackageOverrides [1m[30m=[0m pkgs: {
    vaapiIntel [1m[30m=[0m pkgs[1m[30m.[0mvaapiIntel[1m[30m.[0moverride { enableHybridCodec [1m[30m=[0m [31mtrue[0m; };
  };

[3m[32m#  services.udev.extraRules = ''[0m
[3m[32m#   ACTION=="change", SUBSYSTEM=="backlight", RUN+="${pkgs.coreutils}/bin/chgrp video /sys/class/backlight/%k/brightness"[0m
[3m[32m#   ACTION=="change", SUBSYSTEM=="backlight", RUN+="${pkgs.coreutils}/bin/chmod g+w /sys/class/backlight/%k/brightness"[0m
[3m[32m#   ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="none"#[0m
[3m[32m#	'';[0m
  hardware[1m[30m.[0mopengl [1m[30m=[0m {
    enable [1m[30m=[0m [31mtrue[0m;
    extraPackages [1m[30m=[0m [1m[1m[35mwith[0m pkgs; [
      intel-media-driver [3m[32m# LIBVA_DRIVER_NAME=iHD[0m
      vaapiIntel         [3m[32m# LIBVA_DRIVER_NAME=i965 (older but works better for Firefox/Chromium)[0m
      vaapiVdpau
      libvdpau-va-gl
    ];
  };
}
